# Generated by Django 5.1.4 on 2025-01-04 06:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teammenbers_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammenbers',
            name='research',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
