# Generated by Django 5.1.4 on 2025-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_consultants_alter_teammenbers_consultant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='District in TN')),
            ],
        ),
        migrations.AlterModelOptions(
            name='consultants',
            options={'ordering': ['name'], 'verbose_name_plural': 'consultant type'},
        ),
        migrations.AlterModelOptions(
            name='teammenbers',
            options={'ordering': ['name'], 'verbose_name_plural': 'my team'},
        ),
        migrations.AlterField(
            model_name='teammenbers',
            name='image',
            field=models.ImageField(upload_to='images/teammembers'),
        ),
    ]
