# Generated by Django 5.1.4 on 2025-01-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_districts_alter_consultants_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammenbers',
            name='district',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.districts'),
            preserve_default=False,
        ),
    ]
