# Generated by Django 5.1.4 on 2025-01-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_teammenbers_consultant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMenbers',
            new_name='TeamMembers',
        ),
    ]
