# Generated by Django 5.1.4 on 2025-01-06 07:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_teammenbers_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='district',
            field=models.CharField(choices=[('chennai', 'chennai'), ('vellore', 'vellore'), ('coimbatore', 'coimbatore'), ('erode', 'erode')], default='chennai', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='education',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='research',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='working',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
