# Generated by Django 5.1.4 on 2025-01-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_teammembers_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
