# Generated by Django 5.1.4 on 2025-01-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_teammembers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='image',
        ),
    ]
