# Generated by Django 5.1.4 on 2025-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_teammembers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
