# Generated by Django 5.1.4 on 2025-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teammembers_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='district',
            field=models.CharField(choices=[('chennai', 'chennai'), ('vellore', 'vellore')], default='chennai', max_length=100),
        ),
    ]
