# Generated by Django 5.1.4 on 2025-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_img_teammembers_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'consultants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='consultant',
            field=models.CharField(choices=[('Admiralty and Maritime', 'Admiralty and Maritime'), ('Antitrust & Competition', 'Antitrust & Competition'), ('Compliance, Bribery & Anti-corruption', 'Compliance, Bribery & Anti-corruption'), ('Corporate Insolvency & Restructuring', 'Corporate Insolvency & Restructuring'), ('Employment & Industrial Relations', 'Employment & Industrial Relations'), ('Foreign Investment & Exchange Control', 'Foreign Investment & Exchange Control'), ('Joint Ventures, Foreign & Technical Collaborations', 'Joint Ventures, Foreign & Technical Collaborations'), ('Oil & Gas, Energy and Infrastructure', 'Oil & Gas, Energy and Infrastructure'), ('Project Finance', 'Project Finance'), ('Regulatory Affairs', 'Regulatory Affairs'), ('Technology, Media & Telecommunication', 'Technology, Media & Telecommunication'), ('Aerospace and Defense', 'Aerospace and Defense'), ('Banking & Finance', 'Banking & Finance'), ('Corporate Commercial Advisory', 'Corporate Commercial Advisory'), ('Dispute Resolution', 'Dispute Resolution'), ('environment', 'Environment'), ('Insurance & Reinsurance', 'Insurance & Reinsurance'), ('Intellectual Property', 'Intellectual Property'), ('Mergers & Acquisitions', 'Mergers & Acquisitions'), ('Mining & Resources', 'Mining & Resources'), ('Private Equity, Venture Capital & Funds', 'Private Equity, Venture Capital & Funds'), ('Real Estate', 'Real Estate'), ('Taxation', 'Taxation')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='district',
            field=models.CharField(choices=[('ariyalur', 'Ariyalur'), ('our attorneys', 'our attorneys'), ('chengalpattu', 'Chengalpattu'), ('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('cuddalore', 'Cuddalore'), ('dharmapuri', 'Dharmapuri'), ('dindigul', 'Dindigul'), ('erode', 'Erode'), ('kallakurichi', 'Kallakurichi'), ('kanchipuram', 'Kanchipuram'), ('kanyakumari', 'Kanyakumari'), ('karur', 'Karur'), ('krishnagiri', 'Krishnagiri'), ('madurai', 'Madurai'), ('mayiladuthurai', 'Mayiladuthurai'), ('nagapattinam', 'Nagapattinam'), ('namakkal', 'Namakkal'), ('nilgiris', 'Nilgiris'), ('perambalur', 'Perambalur'), ('pudukottai', 'Pudukottai'), ('ramanathapuram', 'Ramanathapuram'), ('ranipet', 'Ranipet'), ('salem', 'Salem'), ('sivaganga', 'Sivaganga'), ('tenkasi', 'Tenkasi'), ('thanjavur', 'Thanjavur'), ('theni', 'Theni'), ('thoothukudi', 'Thoothukudi'), ('tiruchirappalli', 'Tiruchirappalli'), ('tirunelveli', 'Tirunelveli'), ('tirupattur', 'Tirupattur'), ('tiruppur', 'Tiruppur'), ('tiruvallur', 'Tiruvallur'), ('tiruvannamalai', 'Tiruvannamalai'), ('tiruvarur', 'Tiruvarur'), ('vellore', 'Vellore'), ('viluppuram', 'Villupuram'), ('virudhunagar', 'Virudhunagar')], default='chennai', max_length=100),
        ),
    ]
