# Generated by Django 5.1.4 on 2025-01-22 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_consultants_districts_alter_teammembers_consultant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultants'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.districts'),
        ),
    ]
