# Generated by Django 5.1.4 on 2025-01-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_teammembers_consultant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultants',
            options={'ordering': ['name'], 'verbose_name_plural': 'consultants types'},
        ),
        migrations.CreateModel(
            name='Bloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(upload_to='images/')),
                ('blog_title', models.TextField()),
                ('blog_date', models.DateField()),
                ('blog_content', models.TextField()),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultants')),
            ],
        ),
    ]
