# Generated by Django 5.1.4 on 2025-01-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_consultants_options_bloge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloge',
            options={'ordering': ['blog_date'], 'verbose_name_plural': 'blogs'},
        ),
    ]
