# Generated by Django 5.1.4 on 2025-01-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_bloge_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloge',
            options={},
        ),
    ]
