# Generated by Django 5.1.4 on 2025-01-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_bloge_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloge',
            new_name='Blog',
        ),
    ]
