from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('attorney/', views.attorney, name='attorney'),
    path('practice/', views.practice, name='practice'),
    path('contact/', views.contact, name='contact'),
    path('contact/', views.contact, name='contact'),
    path('index_contact/', views.index_contact, name='index_contact'),
    # path('practice/<slug:practice_slug>/', views.practice_detail, name='practice-detail'),
    path('practice-criminal-law/', views.practice_criminal_law, name='practice-criminal-law'),
    path('practice-civil-law/', views.practice_civil_law, name='practice-civil-law'),
    path('practice-family-law/', views.practice_family_law, name='practice-family-law'),
    path('practice-business-law/', views.practice_business_law, name='practice-business-law'),
    path('practice-education-law/', views.practice_education_law, name='practice-education-law'),
    path('practice-cyber-law/', views.practice_cyber_law, name='practice-cyber-law'),
    path('practice-admiralty-maritime/', views.practice_admiralty_maritime_law, name='practice-admiralty-maritime'),
    path('practice-Antitrust-Competition/', views.practice_Antitrust_Competition_law, name='practice-Antitrust-Competition'),
    path('practice-compliance-bribery/', views.practice_compliance_bribery_law, name='practice-compliance-bribery'),
    path('practice-corporate-insolvency/', views.practice_corporate_insolvency_law, name='practice-corporate-insolvency'),
    path('practice-employment-relations/', views.practice_employment_relations_law, name='practice-employment-relations'),
    path('practice-foreign-investment/', views.practice_foreign_investment_law, name='practice-foreign-investment'),
    path('practice-joint-ventures/', views.practice_joint_ventures_law, name='practice-joint-ventures'),
    path('practice-oil-gas/', views.practice_oil_gas_law, name='practice-oil-gas'),
    path('practice-project-finance/', views.practice_project_finance_law, name='practice-project-finance'),
    path('practice-regulatory-affairs/', views.practice_regulatory_affairs_law, name='practice-regulatory-affairs'),
    path('practice-tech-media/', views.practice_tech_media_law, name='practice-tech-media'),
    path('practice-aerospace-defense/', views.practice_aerospace_defense_law, name='practice-aerospace-defense'),
    path('practice-banking-finance/', views.practice_banking_finance_law, name='practice-banking-finance'),
    path('practice-corporate-advisory/', views.practice_corporate_advisory_law, name='practice-corporate-advisory'),
    path('practice-dispute-resolution/', views.practice_dispute_resolution_law, name='practice-dispute-resolution'),
    path('practice-environment/', views.practice_environment_law, name='practice-environment'),
    path('practice-insurance/', views.practice_insurance_law, name='practice-insurance'),
    path('practice-intellectual-property/', views.practice_intellectual_property_law, name='practice-intellectual-property'),
    path('practice-mergers-acquisitions/', views.practice_mergers_acquisitions_law, name='practice-mergers-acquisitions'),
    path('practice-mining-resources/', views.practice_mining_resources_law, name='practice-mining-resources'),
    path('practice-private-equity/', views.practice_private_equity_law, name='practice-private-equity'),
    path('practice-real-estate/', views.practice_real_estate_law, name='practice-real-estate'),
    path('practice-taxation/', views.practice_taxation_law, name='practice-taxation'),
    path('attorney-details/<int:id>', views.attorney_details, name='attorney-details'),
]